### PR TITLE
[733] Verificationform: update size and placement of logos

### LINKED ISSUE #733: project verification: update placement and sizing of logos
**Problem**: Twitter & Github should be smaller and more aligned - please see designs. 

Currently: 
Screen Shot 2023-01-19 at 11 15 27 AM

Designs: 
Screen Shot 2023-01-19 at 11 22 13 AM

Figma: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2786%3A18722&t=GThTlObelclD5qJy-0

### PR DESCRIPTION
**Pull request by 0xKurt**
fixes #733 

**Design**
image

**Before**
image

**After**
image

### CODE REVIEW

**Comment by 0xKurt** [comment]
In case the deployment links don't show up: https://733-update-logo-size-and-pla.grant-hub.pages.dev/

**Comment by codenamejason** [comment]
@KurtMerbeth this looks great 🔥 one thing I noticed was I had to click next twice to move forward.

This button here =>
Screenshot 2023-01-26 at 12 06 54 PM

**Review by michellema1208 — APPROVED** [review]

**Comment by 0xKurt** [comment]
> @KurtMerbeth this looks great fire one thing I noticed was I had to click next twice to move forward.
> 
> This button here => Screenshot 2023-01-26 at 12 06 54 PM

Not related to this PR, new issue created: #751

**Review by codenamejason — APPROVED** [review]
Nice Job 🔥

**Pull request merged**
