### PR TITLE
431 update project form placeholder text

### LINKED ISSUE #431: create/edit project: update placeholder text on create/edit project form
**User Story** 
As a project owner, 
I want to learn more about what is expected from my answer to each question   
so that I don't input invalid or incorrect answers

**Acceptance Criteria**
GIVEN that I am creating a project 
WHEN I look at the page 
THEN I see informational placeholder text that helps me answer the questions 

The copy for placeholder text should read: 
* Project Website -> "Share your project's website" 
* Project Twitter -> "Share your project's Twitter handle"
* Your Github username -> "Share the GitHub username that you use to contribute to your project" 
* Project Github Organization -> "Share the GitHub organization that your project is a part of" 

**Notes/Assumptions**: 
* N/A

**Product & Design Links**:  
* [Figma link](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2557%3A17537)

**Tech Details**: 
* N/A 

**Open Questions**: 
* N/A

### PR DESCRIPTION
**Pull request by ghostffcode**
Fix for issue #431 

Screen Shot 2022-10-04 at 11 05 50 AM

### CODE REVIEW

**Comment by willsputra** [comment]
lgtm!

**Review by gravityblast — APPROVED** [review]
LGMT!

**Comment by michellema1208** [comment]
hey @ghostffcode love the first quick PR! a few things: 

1. It looks like we're missing the placeholder text update for Project Website - it should read "Share your project's website" instead of "https://gitcoin.co" (original ticket: https://github.com/gitcoinco/grant-hub/issues/431) 

2. I'm also noticing that the placeholder copy for the Twitter, Github, & Github org questions are being cut off because the boxes. Question for @willsputra - should we make the question boxes longer? This is the copy that I drafted 

Your Github username -> "Share the GitHub username that you use to contribute to your project"
Project Github Organization -> "Share the GitHub organization that your project is a part of"

Also open to ideas for shorter copy for the placeholder text! 

**Screenshot:**
Screen Shot 2022-10-04 at 2 52 46 PM

**Comment by ghostffcode** [comment]
> 1. It looks like we're missing the placeholder text update for Project Website - it should read "Share your project's website" instead of "https://gitcoin.co" (original ticket: [create/edit project: update placeholder text on create/edit project form #431](https://github.com/gitcoinco/grant-hub/issues/431))

Just pushed a fix for that. Thanks for pointing it out

Screen Shot 2022-10-04 at 2 44 34 PM

I'll wait on the resolution for the second question to see where we go from there.

**Comment by willsputra** [comment]
@michellema1208 how about:
Project Website -> "Your project's website"
Project Twitter -> "Your project's Twitter handle"
Your Github username -> "GitHub username you use to contribute to the project"
Project Github Organization -> "GitHub org name your project is a part of"

what do you think?

**Comment by michellema1208** [comment]
@willsputra this looks great, thanks Willl! @ghostffcode can you update with this copy? In the off-chance that it's still too long, we can try to make it even shorter

**Comment by ghostffcode** [comment]
Looks great so far

Screen Shot 2022-10-04 at 3 56 28 PM

**Comment by michellema1208** [comment]
@ghostffcode awesome, let's ship it! Thanks @ghostffcode and kudos on your first Grant Hub PR [🔥](https://emojipedia.org/fire/)

**Pull request merged**
