### PR TITLE
Format date and change order of fields in project details

### PR DESCRIPTION
**Pull request by DanieleSalatti**
This addresses #300 

Note that using `toLocaleString` there doesn't seem to be a way to get they days as e.g. "1st", "2nd" but only as "1", "2" etc.

If we want that we might have to write our own date formatting, unless I am missing something. Documentation is [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).

### CODE REVIEW

**Review by codenamejason — COMMENTED** [review]
Dates look good. The only thing I noticed was the alignment is just a bit off in the details.

Screen Shot 2022-09-26 at 9 05 27 AM

**Comment by DanieleSalatti** [comment]
I think our social icons are too small, will try to harmonise that

**Comment by DanieleSalatti** [comment]
Updated. This is the closes I can get it to the Figma with Tailwind only.

qq: why are we not using some icon pack from npm?

**Comment by codenamejason** [comment]
I have had the same issue matching icons

**Review by codenamejason — APPROVED** [review]

**Pull request merged**
