### PR TITLE
59 toast component

### PR DESCRIPTION
**Pull request by schultztimothy**
Adds toast component and implements it throughout app

fixes: #59

### CODE REVIEW

**Comment by schultztimothy** [comment]
> @schultztimothy great job the code looks good!
> 
> Just 2 points on the UX (/cc @michellema1208 )
> 
> 1 - When the toast opens it doesn't close automatically like the one before but the user has to click on the X to close. 2 - When we click "save and publish" we have 3 messages, before tx, during tx, after tx. instead of opening 3 toasts we are using always the same changing the text inside. This means if I close it when the first message is displayed, I never see the second and third one.

> 
> wdyt?
1. Yeah this uses the tailwind ui implementation doesn't have that functionality included by default like the chakra one 😞  @michellema1208 @willsputra what do you all think should the toast fade out after a timeout?

2. This seems like a good question for @michellema1208 or @willsputra . I also wrote a comment here about this: https://github.com/gitcoinco/grants-hub/issues/59. On the contrary do we want to send the user 3 notifications for a tx?   You still do have the block explorer/wallet to track the tx

**Comment by michellema1208** [comment]
@gravityblast @schultztimothy 

- I think it would be cleaner for the toast component to time out! 
- For when the user is publishing something, can we send three transactions (confirm tx, pending tx, success tx) each timing out at about 3-5 seconds?

**Comment by willsputra** [comment]
> @gravityblast @schultztimothy
> 
> * I think it would be cleaner for the toast component to time out!
> * For when the user is publishing something, can we send three transactions (confirm tx, pending tx, success tx) each timing out at about 3-5 seconds?

agree with these!

**Comment by schultztimothy** [comment]
> Title

A new ticket was created to address these suggestions: https://github.com/gitcoinco/grants-hub/issues/102

**Pull request merged**
